version: "3.3"
services:
  app:
    build: 
      args: 
        user: derio
        uid: 1000
      context: ./
      dockerfile: Dockerfile  
    image: sispat-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    depends_on:
      - redis
      - queue
    networks:
      - laravel-eti

  nginx:
    image: nginx:alpine
    ports:
      - 8000:80
    restart: unless-stopped
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - laravel-eti

  db:
    image: mysql:5.7.22
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USERNAME: ${DB_USERNAME}
    volumes:
      - ./.docker/mysql/dbdata:/var/lib/mysql 
    ports:
      - 3307:3306      
    networks:
      - laravel-eti  

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    ports:
      - "8080:80"
    volumes:
      - ./uploads.ini:/usr/local/etc/php/conf.d/php-phpmyadmin.ini
    networks:
      - laravel-eti       

  queue:
    build:
      args:
        user: derio
        uid: 1000
      context: ./
      dockerfile: Dockerfile      
    restart: unless-stopped
    command: "php artisan queue:work"
    volumes: 
      - ./:/var/www
    depends_on: 
      - redis
    networks: 
      - laravel-eti

  redis:
    image: redis:latest
    networks:
      - laravel-eti    

networks:
  laravel-eti:
    driver: bridge
